# Generated by Django 5.2.6 on 2026-02-13 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Customer",
            fields=[
                ("CUSTID", models.AutoField(primary_key=True, serialize=False)),
                ("CUSTNAME", models.CharField(max_length=200)),
                ("CUSTEMAIL", models.EmailField(max_length=254, unique=True)),
                (
                    "DISPSTATUS",
                    models.IntegerField(choices=[(0, "Enabled"), (1, "Disabled")]),
                ),
                ("PRCSDATE", models.DateTimeField(auto_now_add=True)),
            ],
            options={"db_table": "CUSTOMER_MASTER", "ordering": ["-PRCSDATE"],},
        ),
        migrations.CreateModel(
            name="Denomination",
            fields=[
                ("DENOMID", models.AutoField(primary_key=True, serialize=False)),
                ("DENOMVALUE", models.PositiveIntegerField(unique=True)),
                (
                    "DISPSTATUS",
                    models.IntegerField(choices=[(0, "Enabled"), (1, "Disabled")]),
                ),
                ("PRCSDATE", models.DateTimeField(auto_now_add=True)),
            ],
            options={"db_table": "DENOMINATION_MASTER", "ordering": ["-DENOMVALUE"],},
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                ("PRODID", models.AutoField(primary_key=True, serialize=False)),
                ("PRODNAME", models.CharField(max_length=200)),
                ("PRODCODE", models.CharField(max_length=50, unique=True)),
                ("PRODPRI", models.DecimalField(decimal_places=2, max_digits=10)),
                ("PRODTAXPRE", models.DecimalField(decimal_places=2, max_digits=5)),
                (
                    "DISPSTATUS",
                    models.IntegerField(choices=[(0, "Enabled"), (1, "Disabled")]),
                ),
                ("PRCSDATE", models.DateTimeField(auto_now_add=True)),
            ],
            options={"db_table": "PRODUCT_MASTER", "ordering": ["-PRCSDATE"],},
        ),
    ]
