# Generated by Django 6.0.2 on 2026-02-13 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Billing_App", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="PROAVASTOCK",
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
    ]
