# Generated by Django 6.0.2 on 2026-02-13 15:49

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Billing_App", "0002_product_proavastock"),
    ]

    operations = [
        migrations.CreateModel(
            name="Invoice",
            fields=[
                ("INVOICEID", models.AutoField(primary_key=True, serialize=False)),
                ("CUSTEMAIL", models.EmailField(db_index=True, max_length=254)),
                (
                    "GROSSAMT",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=12
                    ),
                ),
                (
                    "TAXAMT",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=12
                    ),
                ),
                (
                    "NETAMT",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=12
                    ),
                ),
                (
                    "ROUNDEDPAYABLE",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=12
                    ),
                ),
                (
                    "PAIDAMT",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=12
                    ),
                ),
                (
                    "BALANCEAMT",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=12
                    ),
                ),
                ("RECEIVED_DENOMS", models.JSONField(blank=True, default=dict)),
                ("CHANGE_DENOMS", models.JSONField(blank=True, default=dict)),
                ("EMAILSENT", models.BooleanField(default=False)),
                ("PRCSDATE", models.DateTimeField(auto_now_add=True)),
            ],
            options={"db_table": "TRANSACTION_MASTER", "ordering": ["-PRCSDATE"],},
        ),
        migrations.CreateModel(
            name="InvoiceItem",
            fields=[
                ("INVOICEITEMID", models.AutoField(primary_key=True, serialize=False)),
                ("UNITPRICE", models.DecimalField(decimal_places=2, max_digits=10)),
                ("TAXPERCENT", models.DecimalField(decimal_places=2, max_digits=5)),
                ("QTY", models.PositiveIntegerField()),
                ("LINESUBTOTAL", models.DecimalField(decimal_places=2, max_digits=12)),
                ("LINETAX", models.DecimalField(decimal_places=2, max_digits=12)),
                ("LINETOTAL", models.DecimalField(decimal_places=2, max_digits=12)),
                ("PRCSDATE", models.DateTimeField(auto_now_add=True)),
                (
                    "INVOICE",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="Billing_App.invoice",
                    ),
                ),
                (
                    "PRODUCT",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="Billing_App.product",
                    ),
                ),
            ],
            options={"db_table": "TRANSACTION_DETAILS", "ordering": ["INVOICEITEMID"],},
        ),
    ]
