# Generated by Django 5.2.6 on 2026-02-13 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Billing_App", "0003_invoice_invoiceitem"),
    ]

    operations = [
        migrations.AddField(
            model_name="invoice",
            name="CUSTNAME",
            field=models.CharField(default="", max_length=200),
        ),
    ]
