# Generated by Django 6.0.2 on 2026-02-14 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Billing_App", "0004_invoice_custname"),
    ]

    operations = [
        migrations.AddField(
            model_name="invoice",
            name="EMAILFAILCOUNT",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="invoice",
            name="EMAILLASTERROR",
            field=models.TextField(blank=True, default=""),
        ),
    ]
